// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoGoMeter.Model;

namespace PoGoMeter.Migrations
{
    [DbContext(typeof(PoGoMeterContext))]
    [Migration("20210503174655_LongUserId")]
    partial class LongUserId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("PoGoMeter")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PoGoMeter.Model.BaseStats", b =>
                {
                    b.Property<short>("Pokemon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Attack")
                        .HasColumnType("smallint");

                    b.Property<short>("Defense")
                        .HasColumnType("smallint");

                    b.Property<short>("Stamina")
                        .HasColumnType("smallint");

                    b.HasKey("Pokemon");

                    b.ToTable("BaseStats");
                });

            modelBuilder.Entity("PoGoMeter.Model.Ignore", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<short>("Pokemon")
                        .HasColumnType("smallint");

                    b.HasKey("UserId", "Pokemon");

                    b.HasIndex("UserId");

                    b.ToTable("Ignore");
                });

            modelBuilder.Entity("PoGoMeter.Model.PokemonName", b =>
                {
                    b.Property<short>("Pokemon")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pokemon");

                    b.ToTable("PokemonName");
                });

            modelBuilder.Entity("PoGoMeter.Model.Stats", b =>
                {
                    b.Property<short>("Pokemon")
                        .HasColumnType("smallint");

                    b.Property<short>("CP")
                        .HasColumnType("smallint");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint");

                    b.Property<byte>("AttackIV")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DefenseIV")
                        .HasColumnType("tinyint");

                    b.Property<byte>("StaminaIV")
                        .HasColumnType("tinyint");

                    b.HasKey("Pokemon", "CP", "Level", "AttackIV", "DefenseIV", "StaminaIV");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("PoGoMeter.Model.Stats", b =>
                {
                    b.HasOne("PoGoMeter.Model.BaseStats", null)
                        .WithMany("Stats")
                        .HasForeignKey("Pokemon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PoGoMeter.Model.BaseStats", b =>
                {
                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
